name: Pipiple to deploy frontend app 

on:
  push:
    branches:
      - main
env:
  IMAGE_FRONTEND_NAME: frontend-image
  IMAGE_TAG: latest
  CONTAINER_NAME: frontend-container

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        run: | 
          git clone https://github.com/franklinfoko/devops-path.git
          ls -l

      - name: Build docker image
        run: | 
          docker build -t ${{env.IMAGE_FRONTEND_NAME}}:${{env.IMAGE_TAG}} devops-path/AWS/project/python-three-tier-app/frontend/
          docker images
      - name: Save Docker Image
        run: |
          echo "${{ secrets.MY_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker tag ${{env.IMAGE_FRONTEND_NAME}}:${{env.IMAGE_TAG}} ghcr.io/${{ github.repository_owner }}/${{env.IMAGE_FRONTEND_NAME}}:${{env.IMAGE_TAG}}
          docker push ghcr.io/${{ github.repository_owner }}/${{env.IMAGE_FRONTEND_NAME}}:${{env.IMAGE_TAG}}

  Test-image:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Test Image
        run: |
          echo Test acceptance
          echo "${{ secrets.MY_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker run -d --name ${{ env.CONTAINER_NAME }} ghcr.io/${{ github.repository_owner }}/${{env.IMAGE_FRONTEND_NAME}}:${{env.IMAGE_TAG}}
          sleep 5
          export IP_CONTAINER=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ env.CONTAINER_NAME }} )
          curl -I http://$IP_CONTAINER:5000

          docker rm -f ${{ env.CONTAINER_NAME }}

  # Push-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Push Image on ECR 
  #       run: |
  #         
  #         aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 891377281461.dkr.ecr.ca-central-1.amazonaws.com
  #         docker tag frontend-image:latest 891377281461.dkr.ecr.ca-central-1.amazonaws.com/my-ecr-repo:latest
  #         docker push 891377281461.dkr.ecr.ca-central-1.amazonaws.com/my-ecr-repo:latest














      
          

   